### ISSUE TITLE
Rendering errors are not shown in the menu

### ISSUE THREAD

**Issue by chrahunt** [chrahunt/TagProReplays#100]
As mentioned [here](https://www.reddit.com/r/TagPro/comments/5dh44h/tagpro_replay_extension_help/da4snyk/), on render failure we are not correctly displaying the ERROR message in the rendering column on the menu.

To test, intentionally create/throw some error in Whammy and ensure it is caught.

**Comment by chrahunt** [comment]
Having trouble reproducing. @ballparts, any more information on what went wrong for that user?

**Comment by ballparts** [comment]
The description from that user wasn't very clear. At first it sounded like the replay failed immediately and then moved on to the next replay without showing the ERROR indicator, which isn't in line with the Whammy error. But the screenshot the user sent indicated the replay rendered for a typical amount of time before failing (with the "Uncaught Frame XXX has a different width" error). 

If it's working in your tests, I'd say let it go unless someone else brings it up. Fingers crossed no one will have to see that error indicator any time soon!

**Comment by ballparts** [comment]
I should add that the user did say that the extension did move on to the next replay successfully despite not rendering the first one, which is the main point of handling the Whammy error. So I stand by not spending too much time on this unless it comes up again or we can replicate the issue later.

**Comment by chrahunt** [comment]
Sounds good to me.
