### ISSUE TITLE
Validation error

### ISSUE THREAD

**Issue by havemad** [chrahunt/TagProReplays#149]
http://dropcanvas.com/IQ48V41P2h3hsO 
https://gyazo.com/fec7a33317d59f5ad5d46d6cd84834b4

I'm not quite sure why it won't let me import/view this replay. Thanks in advance for any  help :)

**Comment by chrahunt** [comment]
Thanks for the report. The fix for this will be pushed out soon and your extension should update in a few hours at most.

**Comment by havemad** [comment]
thanks a lot 👍
