### ISSUE TITLE
Menu not showing replays and record button not working

### ISSUE THREAD

**Issue by zeeres** [chrahunt/TagProReplays#154]
I have the issue that I had 30 replays in the extension, but they wouldn't show in the menu, and I can't record any clips (or at least the "Saved!" message doesn't show). I downloaded and deleted them now with the Helper, but even after reinstalling the extension the "Saved!" message still doesn't appear after pushing the record button.

This is what the console prints after pushing the button:
```
tpr:recording:info Record hotkey pressed. +0ms
recording.js:288 tpr:recording:info Sending replay to content script. +15ms
content.js:2676 tpr:content:info Received recording, sending to background page. +15s
tagpro-chord.koalabeast.com/:1 Error in event handler for (unknown): TypeError: Cannot read property 'failed' of undefined
at chrome.runtime.sendMessage (chrome-extension://ejbnakhldlocljfcglmeibhhdnmmcodh/js/content.js:24971:27)
```

And if I run the Helper again, this is what I get:
```
Helper is ready.
Helper.show_number_of_replays()
VM54:85 Retrieving...
undefined
VM54:47 Uncaught (in promise) DOMException: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.(…)Promise @ VM54:47get_number_of_replays @ VM54:46show_number_of_replays @ VM54:86(anonymous function) @ VM67:1
```
Maybe because there's no replays left in the extension?
I also tried with a clean new chrome profile, same thing there. Running Chromium Version 53.0.2785.143 (64-bit) on Linux.

This is the background page after browsing to TagPro, opening the Replays-Menu and pressing the record button:
```
tpr:textures:info Loading textures +0ms
background.js:8781 tpr:renderer:info Loading renderer. +3ms
background.js:43242 Uncaught TypeError: document.body.append is not a function
background.js:8781 tpr:track:debug Received event from content script. +16s
background.js:8781 tpr:track:debug Received tracking event: Menu Opened +1ms
```
If you need further information, I would be happy to provide it!

**Comment by chrahunt** [comment]
Thank you for the detailed report.

I think I know the problem. I used [`append`](https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/append) instead of [`appendChild`](https://developer.mozilla.org/en-US/docs/Web/API/Node/appendChild), the former only being available in Chrome 54+. The Helper error is a side-effect, caused by the database having not been created yet in the newly installed extension, since the error occurred before we try to open/create it. I will push out an update soon.
