### ISSUE TITLE
Not working on Chromebook

### ISSUE THREAD

**Issue by nate1097** [chrahunt/TagProReplays#162]
I have a chromebook, and it seems the Replay extension is sometimes downloading the replay as a .txt rather than saving it to the replays function, which makes the replay useless. I also play with friends on some of the newcompte sites, and it seems these replays disappear when I switch back to koalabeast. Any ideas? Thanks

**Comment by chrahunt** [comment]
The extension downloads the file because it detected something wrong with the replay. This is new, before it would just silently fail. You can take the file and import it into the extension by using the import button as seen here:

![image](https://cloud.githubusercontent.com/assets/2312275/21297653/02c49300-c552-11e6-9013-b29ddc9edc99.png)

If there really is something wrong with it then it should display an error message that you can copy here along with a link so I can download the replay.

**Comment by chrahunt** [comment]
Regarding your second question, it should not matter which site you are playing on when you record the replay. The replays get saved to the extension which is not site-specific. Can you provide any more information that would help troubleshoot this? At this point I can't even seem to get the extension working on, for example, maptest2.newcompte.fr. Are you able to see the record button and the 'Saved!' feedback when you record a replay?

**Comment by nate1097** [comment]
Yes, the saved message shows up, the replay just isn't saved. I tried importing them but it didn't work, is there any way I could've done something wrong? Thanks so much!

Nate

**Comment by chrahunt** [comment]
> I tried importing them but it didn't work

Can you be more specific? Step-by-step would help, for example:

1. I navigate to a tagpro server homepage
2. Open the TagPro Replays menu
3. Click the import button
4. Select a replay that downloaded when recording before
5. A message comes up saying the replay is invalid with the message: "..."

If that is what happened, then can you upload the replay to dropcanvas.com and send me the link? I should be able to take a look at it.

Also, in case it's relevant, can you provide your Chrome and operating system version?

**Comment by nate1097** [comment]
1. I go to home page
2. I click on replays button
3. I click import button
4. I select replay file
5. Validation error: scheme
Validation failiure; data.chat[0] should match exactly one scheme in oneOf

I am on a Google Chromebook and fully up to date

**Comment by nate1097** [comment]
externalfile:drive-e4ad58c5a7181b43185486d2b7ca782a8a0f04e1/root/0007_replay_1482031112634DATE1482031112634.txt

And here is the link

**Comment by chrahunt** [comment]
It doesn't look like the link came through on GitHub. Can you try once more? It might help to post on the site itself.

**Comment by chrahunt** [comment]
Hi @nate1097, please check #185 for updates as it may relate to your issue. If you see this and #185 is already closed, try to upload your replay. If it fails please come back and we can try to sort it out.
