### ISSUE TITLE
Replays rejected with spawns that have additional properties

### ISSUE THREAD

**Issue by wutTP** [chrahunt/TagProReplays#172]
Your replay (0098_replay_1484993663510DATE1484993663510.txt) had a problem:
Validation error: schema validation failure; data.spawns[1] should NOT have additional properties

http://dropcanvas.com/#PZstdmY63QK41t

**Comment by chrahunt** [comment]
Hi, sorry I have let this dropcanvas expire. Do you mind re-uploading it?

**Comment by wutTP** [comment]
Hi, I haven't 'used' TagProReplays in a long time, but I wanted to render 1 of my replays (I have been saving replays, but it just downloads a text file) today and it doesn't work:

Import error
Your replay (0045_replay_1496595814353DATE1496595814353.txt) had a problem:
Validation error: schema validation failure; data/clock/0 should be string
If you believe this was in error then upload your replay to dropcanvas and make an issue here with the link and message above.

http://dropcanvas.com/yoiq6

**Comment by chrahunt** [comment]
Thanks. I see additional error reports like this:

```
"Reason":"Validation error: schema validation failure; data/spawns/0 should NOT have additional properties",
"Extended":"should NOT have additional properties;
key:diedAt;value:163479.565;",
"URL":"http://tagpro-diameter.koalabeast.com:8000/"
```

Not sure when this happens, but I can add it to the validation.
