### ISSUE TITLE
Rendering problem

### ISSUE THREAD

**Issue by samouree** [chrahunt/TagProReplays#190]
I got this error when trying to render a replay:

Your replay (tagpro-1499345871420.txt) had a problem:
Validation error: schema validation failure; data/clock/0 should be string

Here is the canvas: http://dropcanvas.com/#ALzi9pB830F2R6

**Comment by chrahunt** [comment]
The canvas appears to have expired, can you reupload?

**Comment by chrahunt** [comment]
Closing this, please create a new issue if you encounter this problem again.
