### ISSUE TITLE
Calculation of angle?

### ISSUE THREAD

**Issue by nirajpandkar** [chrahunt/TagProReplays#213]
This is a question than an issue.

Where exactly are you calculating the angle or obtaining it? Can you point me to the file or file number to be exact? 
I saw an initialization of angle attribute to zeros [here](https://github.com/chrahunt/TagProReplays/blob/master/src/js/recording.js#L126)

If it's only obtained, how is the angle calculated? Thanks.

**Comment by ballparts** [comment]
Angle is read from the `tagpro.players` object directly. It is calculated by client-side tagpro code. General info about the `players` object here: https://www.reddit.com/r/TagPro/wiki/api#wiki_player_object

**Comment by chrahunt** [comment]
Specifically to answer your question, the setting of `angle` is done in the loop here: [`recording.js:157`](https://github.com/chrahunt/TagProReplays/blob/0e0619724a4a5d57463cf73f6c6de59db843a121/src/js/recording.js#L157).

**Comment by nirajpandkar** [comment]
Sorry for late reply. 

@ballparts Yeah I had checked out the API as well as skimmed the code superficially but couldn't find the source for calculating angle. Thanks for the link though:+1:

@chrahunt Thanks for pointing it  out 👍 Will check

**Comment by nirajpandkar** [comment]
Just checked the file @chrahunt. I am still not getting how angle would be calculated?

Actually what I'm trying to do is obtain the **direction** in which the player is going. And I thought _angle would be an indicator of that attribute_. But the angles which I saw till now were in the range from -7 to 5, something along these terms.

What I would specifically like to know is the **reference** to which angle is calculated so that I can make sense of the given angles and determine the direction.

On this [line](https://github.com/chrahunt/TagProReplays/blob/0e0619724a4a5d57463cf73f6c6de59db843a121/src/js/recording.js#L126), the angle variable is being initialized but didn't see any modification being done later.

How would you suggest I determine direction if not via angle?

**Comment by ballparts** [comment]
@nirajpandkar  Angle refers to the rotation of the ball, which is independent of the direction the ball is traveling. If you are only looking at the information contained in a replay file, you'd need to calculate direction based on the change in x and y position between any two frames. 

But if you're getting the information from the `tagpro.players` object in an actual tagpro game, you can get the direction from the `lx` and `ly` attributes, which give the last observed velocity in each direction. This is only updated about 4 times a second, though, so you may want to calculate the velocity yourself, as snaps did in [this script.](https://www.reddit.com/r/tagprobots/comments/2t9ucm/tip_use_box2d_to_get_velocity_lx_and_ly_are_too/cnxf3ey/)

**Comment by nirajpandkar** [comment]
@ballparts Oh thanks for clarifying that. That's what I was looking for :smile: 

I think change in x and y position should do it :+1:
