### ISSUE TITLE
Downloading clips and raw data not working suddenly

### ISSUE THREAD

**Issue by zmunro** [chrahunt/TagProReplays#216]
Not sure what has changed in the past few days but the extension no longer lets you download clips or their raw data. I tried to use the helper script and run `Helper.download_replays(1)` and it looks like it works but nothing ever actually gets downloaded. Posted in the subreddit and Ping Tut has also been experiencing this issue. Please help :(

**Comment by chrahunt** [comment]
Hi, I have tested this and can confirm that it happens for me too. This is likely related to eligrey/FileSaver.js#408.
