### ISSUE TITLE
Improve default replay name

### ISSUE THREAD

**Issue by ballparts** [chrahunt/TagProReplays#22]
maybe “mapname-date". maybe have user able to decide among various keywords they can order how they like

**Comment by chrahunt** [comment]
Based on the suggestion [here](https://www.reddit.com/r/TagPro/comments/5h1xwp/question_for_tagproreplays_users/daxopkf/), goal right now is just to have a name of the format `{i:0>4}_replay_{timestamp}`. Everything else can be done via tags as mentioned in #56.
