### ISSUE TITLE
Several suggestions

### ISSUE THREAD

**Issue by ballparts** [chrahunt/TagProReplays#36]
Some new suggestions:

1. Action meter/info: Icon if you capped in this replay(I think those events are recorded too, right? Or just positions?)
2. Icon if you get really close to enemies while having flag (High amount of this = probably nice juke clip)
3. Icon if you have a X amount of kills with a tagpro
4. Icon if you have X amount of returns (for example, 4 returns in a short clip = lots of flaccids from other team or just good defense)

These icons can be used to get an indication of what kind of replay it will be. In case you want to make a cool montage of caps, you can just filter out all the replays where you don't even cap etc.

If you don't want icons, but just numbers: "Caps: 1 | Returns: 0 | Tags: 1"
Then maybe calculate an action value from those numbers, shown as a bar or something

-Indieveloper

**Comment by chrahunt** [comment]
This is going to be closed in favor of the more likely implementation detailed in #56.
