### ISSUE TITLE
Separate renderer from Chrome extension

### ISSUE THREAD

**Issue by celtric** [chrahunt/TagProReplays#4]
A few months from now (hope the extension is still alive by then!), the logic of both the extension and the TagPro renderer will probably have changed. Imagine it's January 2015 and we want to replay a JSON file from August 2014. Cloning this repository and trying to execute it may give problems, as the code that now runs on Chrome might no be compatible with the Chrome browser we have in January (although the renderer should work fine).

This on its own might not be worth the hassle, but here comes the second question: how independent is the renderer from the browser? Could a Node.js module render it with a DOM/Canvas implementation? That could be of help, as the renderer right now takes a lot of time and can't be paused easily, whereas with a Node.js module, people could leave background processes running at night, on idle time, etc.

**Comment by chrahunt** [comment]
The most recent version being worked on in [this](https://github.com/chrahunt/TagProReplays/tree/use-new-format) branch uses JSON Schema to define the format of replays as they've appeared up to this point (`src/schemas/1`), taking into account various changes and bugs that resulted in additional properties being present. The new format of the replays is defined in `src/schemas/2` and code for validation and conversion is included in `src/js/modules` in `validation.js` and `conversion.js`. The replays present in the database will always be current, and any required changes will be applied when the database is upgraded. Imported replays of an older version are converted to the most recent version by applying successive transformations to take it from the current version to the next, to the next, until the the replay is up to date. This takes care of the first question and should definitely help with your followup concerning documentation. The converter is essentially the parser you mention. I do need to refactor it so it makes sense for future versions, and thinking about it like that could be a good place to start.

You're right about the time it takes to render the replays. I've offset the inconvenience by structuring the rendering such that it can be paused, cancelled, and gives other code in the event loop a chance to run, but there really isn't a substitute for a faster renderer.

At this point I think the renderer is about as separate from the browser as canvas is. If there's a Node implementation, then it shouldn't be difficult to create a separate module that can work with it. I found the node-canvas module [here](https://github.com/Automattic/node-canvas) but haven't taken a minute to see if `image/webp` is supported.

**Comment by chrahunt** [comment]
This is out of scope for the extension. JSON schema definitions for the replay files have been added to address #97 and speeding up in-extension rendering is being tracked with #145. People are free to make out-of-app renderers using the provided information.
