### ISSUE TITLE
Remove hover preview

### ISSUE THREAD

**Issue by chrahunt** [chrahunt/TagProReplays#54]
This feature may be added again in the future, but at this point it's just in the way.

**Comment by ballparts** [comment]
Might be worth ripping this out of 1.X as well, since it is responsible for the crashes people have when they have too many replays (AFAIK, but it might also be caused by the hover metadata to a much lesser degree).  I could work on this if you think it's worth doing.

**Comment by chrahunt** [comment]
Yeah, I think it is worth it.

**Comment by chrahunt** [comment]
Fixed by #87.
