### ISSUE TITLE
Add an option to have a different texture for your ball

### ISSUE THREAD

**Issue by nrabins** [chrahunt/TagProReplays#9]
This would allow for an additional layer of continuity between replays in montages.

**Comment by ballparts** [comment]
This is interesting, but it is not a high priority at this point. It'll definitely stay on the to-do list.

**Comment by ballparts** [comment]
what if you could select which team you are on at all times. the extension would flip the colors of all relevant map features and the score (could be confusing for things like team boosts).  probably it is less work and more straightforward to do your suggestion.

**Comment by nrabins** [comment]
I think that could work (I probably wouldn't use it though). You'd probably
want to flip the whole map so teams would be on the correct side. All in
all, probably not worth it.

**Comment by chrahunt** [comment]
Closing this, very little to gain but adds complexity.
